
tasks:
  - name: Steedos
    command: |
      cd steedos-enterprise
      docker-compose up -d

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    visibility: public

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
