version: "3.9"

services:
  steedos:
    image: steedos/steedos-community:2022.6
    command: "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "steedos-packages:/app/.steedos"
    environment:
      - ROOT_URL=http://steedos-community:3000 #在此填入客户端访问服务输入的域名（或IP）和端口
      - PORT=3000 #在此填入服务运行的端口
      - MONGO_URL=mongodb://root:password123@mongodb:27017/steedos?authSource=admin&replicaSet=replicaset&readPreference=primary&ssl=false
      - MONGO_OPLOG_URL=mongodb://root:password123@mongodb:27017/local?authSource=admin&replicaSet=replicaset&readPreference=primary&ssl=false
      - STEEDOS_PUBLIC_PAGE_ASSETURLS=https://unpkg.com/@steedos-ui/builder-widgets@2.2.20/dist/assets.json
      - STEEDOS_UNPKG_URL=https://npm.elemecdn.com
      - STEEDOS_CFS_STORE=S3
      - STEEDOS_CFS_AWS_S3_ENDPOINT=http://minio:9000
      - STEEDOS_CFS_AWS_S3_FORCE_PATH_STYLE=true
      - STEEDOS_CFS_AWS_S3_BUCKET=steedos-prod
      - STEEDOS_CFS_AWS_S3_ACCESS_KEY_ID=minio-root-user  # 此处必须修改为 minio 中的 MINIO_ROOT_USER
      - STEEDOS_CFS_AWS_S3_SECRET_ACCESS_KEY=minio-root-password # 此处必须修改为 minio 中的 MINIO_ROOT_PASSWORD
      - TRANSPORTER=nats://nats:4222
      - CACHER=redis://redis:6379
      - INSTANCES=1 # Nodejs Cluster 集群进程数
    depends_on:
      - redis
      - mongodb-primary
      - nats
    
  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
 
  nats:
    image: steedos/nats:2.8.4
    environment:
      - MAX_PAYLOAD=4096000 #4MB
    ports:
      - "4222:4222"
      - "8222:8222" # monitor port

  minio:
    image: bitnami/minio:2022.6.11
    environment:
      - MINIO_ROOT_USER=minio-root-user # 此处必须修改
      - MINIO_ROOT_PASSWORD=minio-root-password # 此处必须修改
      - MINIO_DEFAULT_BUCKETS=steedos-prod
    volumes:
      - steedos-minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001" 
  
  mongodb:
    image: 'bitnami/mongodb:4.4'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'steedos-mongo-data:/bitnami'


volumes:
  steedos-mongo-data:
  steedos-packages:
  steedos-minio-data:
